TICKERS = [
    ('MSFT', 'Microsoft'),
    ('AAPL', 'Apple'),
    ('AMZN', 'Amazon.com'),
    ('FB', 'Facebook'),
    ('BRK.B', 'Berkshire Hathaway'),
    ('JPM', 'JPMorgan Chase'),
    ('GOOG', 'Alphabet'),
    ('GOOGL', 'Alphabet'),
    ('JNJ', 'Johnson & Johnson'),
    ('V', 'Visa'),
    ('PG', 'Procter & Gamble'),
    ('XOM', 'Exxon Mobil'),
    ('BAC', 'Bank of America'),
    ('T', 'AT&T'),
    ('DIS', 'Walt Disney'),
    ('UNH', 'UnitedHealth Group'),
    ('MA', 'Mastercard'),
    ('INTC', 'Intel'),
    ('VZ', 'Verizon Communications'),
    ('HD', 'Home Depot'),
    ('MRK', 'Merck & Co'),
    ('CVX', 'Chevron'),
    ('WFC', 'Wells Fargo'),
    ('PFE', 'Pfizer'),
    ('KO', 'Coca-Cola'),
    ('CMCSA', 'Comcast'),
    ('BA', 'Boeing'),
    ('CSCO', 'Cisco Systems'),
    ('PEP', 'PepsiCo'),
    ('C', 'Citigroup'),
    ('WMT', 'Walmart'),
    ('ABT', 'Abbott Laboratories'),
    ('ADBE', 'Adobe'),
    ('MDT', 'Medtronic'),
    ('MCD', "McDonald's"),
    ('CRM', 'Salesforce.com'),
    ('AMGN', 'Amgen'),
    ('NFLX', 'Netflix'),
    ('NVDA', 'NVIDIA'),
    ('COST', 'Costco Wholesale'),
    ('ABBV', 'AbbVie'),
    ('PM', 'Philip Morris Intl'),
    ('HON', 'Honeywell International'),
    ('ACN', 'Accenture'),
    ('PYPL', 'PayPal Holdings'),
    ('AVGO', 'Broadcom'),
    ('TMO', 'Thermo Fisher Scientific'),
    ('UNP', 'Union Pacific'),
    ('ORCL', 'Oracle'),
    ('UTX', 'United Technologies'),
    ('IBM', 'IBM'),
    ('NKE', 'Nike'),
    ('NEE', 'NextEra Energy'),
    ('TXN', 'Texas Instruments'),
    ('LIN', 'Linde'),
    ('SBUX', 'Starbucks'),
    ('LLY', 'Eli Lilly'),
    ('GE', 'General Electric'),
    ('CVS', 'CVS Health'),
    ('MMM', '3M'),
    ('LMT', 'Lockheed Martin'),
    ('QCOM', 'Qualcomm'),
    ('AMT', 'American Tower'),
    ('DHR', 'Danaher'),
    ('BMY', 'Bristol-Myers Squibb'),
    ('MO', 'Altria Group'),
    ('LOW', "Lowe's Companies"),
    ('USB', 'U.S. Bancorp'),
    ('GILD', 'Gilead Sciences'),
    ('FIS', 'Fidelity National Info'),
    ('UPS', 'United Parcel Service'),
    ('AXP', 'American Express'),
    ('CAT', 'Caterpillar'),
    ('BKNG', 'Booking Holdings'),
    ('CHTR', 'Charter Communications'),
    ('MDLZ', 'Mondelez International'),
    ('CI', 'Cigna'),
    ('ADP', 'Automatic Data Processing'),
    ('TJX', 'TJX Companies'),
    ('ANTM', 'Anthem'),
    ('CME', 'CME Group'),
    ('GS', 'Goldman Sachs Group'),
    ('BDX', 'Becton, Dickinson'),
    ('CB', 'Chubb'),
    ('ISRG', 'Intuitive Surgical'),
    ('D', 'Dominion Energy'),
    ('PNC', 'PNC Financial Services Gr'),
    ('INTU', 'Intuit'),
    ('COP', 'ConocoPhillips'),
    ('FISV', 'Fiserv'),
    ('SYK', 'Stryker'),
    ('SPGI', 'S&P Global'),
    ('SO', 'Southern'),
    ('DUK', 'Duke Energy'),
    ('TGT', 'Target'),
    ('MS', 'Morgan Stanley'),
    ('AGN', 'Allergan'),
    ('RTN', 'Raytheon'),
    ('BSX', 'Boston Scientific'),
    ('CL', 'Colgate-Palmolive'),
    ('BLK', 'BlackRock'),
    ('PLD', 'Prologis'),
    ('SCHW', 'Charles Schwab'),
    ('ZTS', 'Zoetis'),
    ('CSX', 'CSX'),
    ('VRTX', 'Vertex Pharmaceuticals'),
    ('CCI', 'Crown Castle Intl'),
    ('NOC', 'Northrop Grumman'),
    ('BIIB', 'Biogen'),
    ('MMC', 'Marsh & McLennan'),
    ('GPN', 'Global Payments'),
    ('AMAT', 'Applied Materials'),
    ('NOW', 'ServiceNow'),
    ('DE', 'Deere'),
    ('ICE', 'Intercontinental Exchange'),
    ('MU', 'Micron Technology'),
    ('APD', 'Air Products & Chemicals'),
    ('PSX', 'Phillips 66'),
    ('ITW', 'Illinois Tool Works'),
    ('NSC', 'Norfolk Southern'),
    ('EW', 'Edwards Lifesciences'),
    ('SLB', 'Schlumberger'),
    ('DD', 'DuPont de Nemours'),
    ('EQIX', 'Equinix'),
    ('AON', 'Aon'),
    ('SHW', 'Sherwin-Williams'),
    ('ILMN', 'Illumina'),
    ('COF', 'Capital One Financial'),
    ('KMB', 'Kimberly-Clark'),
    ('ECL', 'Ecolab'),
    ('SPG', 'Simon Property Group'),
    ('HUM', 'Humana'),
    ('AIG', 'American International Gr'),
    ('EMR', 'Emerson Electric'),
    ('GM', 'General Motors'),
    ('WBA', 'Walgreens Boots Alliance'),
    ('AEP', 'American Electric Power'),
    ('LHX', 'L3Harris Technologies'),
    ('WM', 'Waste Management'),
    ('EL', 'Estee Lauder Cos'),
    ('EXC', 'Exelon'),
    ('PGR', 'Progressive'),
    ('GD', 'General Dynamics'),
    ('AMD', 'Advanced Micro Devices'),
    ('ROST', 'Ross Stores'),
    ('ATVI', 'Activision Blizzard'),
    ('BK', 'Bank of New York Mellon'),
    ('TFC', 'Truist Financial'),
    ('BAX', 'Baxter International'),
    ('ADI', 'Analog Devices'),
    ('SYY', 'Sysco'),
    ('EOG', 'EOG Resources'),
    ('AFL', 'Aflac'),
    ('DG', 'Dollar General'),
    ('SRE', 'Sempra Energy'),
    ('MPC', 'Marathon Petroleum'),
    ('MET', 'MetLife'),
    ('ADSK', 'Autodesk'),
    ('DOW', 'Dow'),
    ('VLO', 'Valero Energy'),
    ('ETN', 'Eaton'),
    ('LRCX', 'Lam Research'),
    ('FDX', 'FedEx'),
    ('MAR', 'Marriott International'),
    ('KMI', 'Kinder Morgan'),
    ('PRU', 'Prudential Financial'),
    ('ROP', 'Roper Technologies'),
    ('MCO', "Moody's"),
    ('HCA', 'HCA Healthcare'),
    ('ALL', 'Allstate'),
    ('TRV', 'Travelers Companies'),
    ('F', 'Ford Motor'),
    ('CTSH', 'Cognizant Tech Solns'),
    ('OXY', 'Occidental Petroleum'),
    ('JCI', 'Johnson Controls Intl'),
    ('ORLY', "O'Reilly Automotive"),
    ('DAL', 'Delta Air Lines'),
    ('XEL', 'Xcel Energy'),
    ('GIS', 'General Mills'),
    ('IR', 'Ingersoll-Rand'),
    ('PSA', 'Public Storage'),
    ('WELL', 'Welltower'),
    ('NEM', 'Newmont Goldcorp'),
    ('TEL', 'TE Connectivity'),
    ('STZ', 'Constellation Brands'),
    ('APH', 'Amphenol'),
    ('YUM', 'Yum Brands'),
    ('PPG', 'PPG Industries'),
    ('HLT', 'Hilton Worldwide Holdings'),
    ('PEG', 'Public Service Enterprise'),
    ('AVB', 'AvalonBay Communities'),
    ('ZBH', 'Zimmer Biomet Holdings'),
    ('EA', 'Electronic Arts'),
    ('HPQ', 'HP'),
    ('EQR', 'Equity Residential'),
    ('REGN', 'Regeneron Pharmaceuticals'),
    ('OKE', 'ONEOK'),
    ('INFO', 'IHS Markit'),
    ('TROW', 'T. Rowe Price Group'),
    ('VFC', 'VF'),
    ('AZO', 'AutoZone'),
    ('ED', 'Consolidated Edison'),
    ('CMI', 'Cummins'),
    ('PCAR', 'PACCAR'),
    ('TDG', 'TransDigm Gr'),
    ('EBAY', 'eBay'),
    ('STT', 'State Street'),
    ('WEC', 'WEC Energy Group'),
    ('LUV', 'Southwest Airlines'),
    ('MSI', 'Motorola Solutions'),
    ('PAYX', 'Paychex'),
    ('WMB', 'Williams Companies'),
    ('DFS', 'Discover Financial'),
    ('SBAC', 'SBA Communications'),
    ('ES', 'Eversource Energy'),
    ('MCK', 'McKesson'),
    ('IQV', 'IQVIA Holdings'),
    ('FLT', 'Fleetcor Technologies'),
    ('TSN', 'Tyson Foods'),
    ('KLAC', 'KLA'),
    ('FE', 'FirstEnergy'),
    ('ALXN', 'Alexion Pharmaceuticals'),
    ('PH', 'Parker Hannifin'),
    ('WLTW', 'Willis Towers Watson'),
    ('DLR', 'Digital Realty Trust'),
    ('CNC', 'Centene'),
    ('A', 'Agilent Technologies'),
    ('TMUS', 'T-Mobile US'),
    ('EIX', 'Edison Intl'),
    ('PPL', 'PPL'),
    ('O', 'Realty Income'),
    ('VRSK', 'Verisk Analytics'),
    ('APTV', 'Aptiv'),
    ('SWK', 'Stanley Black & Decker'),
    ('ADM', 'Archer-Daniels Midland'),
    ('TWTR', 'Twitter'),
    ('LYB', 'LyondellBasell Industries'),
    ('XLNX', 'Xilinx'),
    ('ETR', 'Entergy'),
    ('MNST', 'Monster Beverage'),
    ('NTRS', 'Northern Trust'),
    ('ROK', 'Rockwell Automation'),
    ('DTE', 'DTE Energy'),
    ('SYF', 'Synchrony Finl'),
    ('CERN', 'Cerner'),
    ('GLW', 'Corning'),
    ('AME', 'AMETEK'),
    ('MCHP', 'Microchip Technology'),
    ('HIG', 'Hartford Financial Servs'),
    ('HSY', 'Hershey'),
    ('FITB', 'Fifth Third Bancorp'),
    ('MTB', 'M&T Bank'),
    ('WY', 'Weyerhaeuser'),
    ('MSCI', 'MSCI'),
    ('BLL', 'Ball'),
    ('AWK', 'American Water Works Co'),
    ('KR', 'Kroger'),
    ('VTR', 'Ventas'),
    ('IDXX', 'IDEXX Laboratories'),
    ('DLTR', 'Dollar Tree'),
    ('RMD', 'ResMed'),
    ('AMP', 'Ameriprise Financial'),
    ('ANSS', 'Ansys'),
    ('PXD', 'Pioneer Natural Resources'),
    ('CTAS', 'Cintas'),
    ('FTV', 'Fortive'),
    ('LVS', 'Las Vegas Sands'),
    ('SNPS', 'Synopsys'),
    ('MKC', 'McCormick & Co'),
    ('CMG', 'Chipotle Mexican Grill'),
    ('HPE', 'Hewlett Packard'),
    ('RCL', 'Royal Caribbean Cruises'),
    ('ESS', 'Essex Property Trust'),
    ('UAL', 'United Airlines Holdings'),
    ('FAST', 'Fastenal'),
    ('ALGN', 'Align Tech'),
    ('KEYS', 'Keysight Technologies'),
    ('BXP', 'Boston Properties'),
    ('VRSN', 'VeriSign'),
    ('CDNS', 'Cadence Design Systems'),
    ('CDW', 'CDW'),
    ('CTVA', 'Corteva'),
    ('KEY', 'KeyCorp'),
    ('CBRE', 'CBRE Group'),
    ('KHC', 'Kraft Heinz'),
    ('VMC', 'Vulcan Materials'),
    ('RSG', 'Republic Services'),
    ('BBY', 'Best Buy Co'),
    ('CLX', 'Clorox'),
    ('DHI', 'D.R. Horton'),
    ('ARE', 'Alexandria Real Estate'),
    ('HAL', 'Halliburton'),
    ('AEE', 'Ameren'),
    ('IP', 'International Paper'),
    ('CCL', 'Carnival'),
    ('CPRT', 'Copart'),
    ('MTD', 'Mettler-Toledo Intl'),
    ('CMS', 'CMS Energy'),
    ('CHD', 'Church & Dwight Co'),
    ('AJG', 'Arthur J. Gallagher'),
    ('OMC', 'Omnicom Group'),
    ('CFG', 'Citizens Financial Group'),
    ('PEAK', 'Healthpeak Properties'),
    ('NUE', 'Nucor'),
    ('EFX', 'Equifax'),
    ('SWKS', 'Skyworks Solutions'),
    ('LH', 'Laboratory Corp'),
    ('INCY', 'Incyte'),
    ('LEN', 'Lennar'),
    ('MLM', 'Martin Marietta Materials'),
    ('AMCR', 'Amcor'),
    ('MGM', 'MGM Resorts Intl'),
    ('RF', 'Regions Financial'),
    ('FCX', 'Freeport-McMoRan'),
    ('CAH', 'Cardinal Health'),
    ('TFX', 'Teleflex'),
    ('CINF', 'Cincinnati Financial'),
    ('DOV', 'Dover'),
    ('K', 'Kellogg'),
    ('WCG', 'WellCare Health Plans'),
    ('KMX', 'CarMax'),
    ('HES', 'Hess'),
    ('CE', 'Celanese'),
    ('COO', 'Cooper Companies'),
    ('MAA', 'Mid-America Apartment'),
    ('HBAN', 'Huntington Bancshares'),
    ('MXIM', 'Maxim Integrated Products'),
    ('KSU', 'Kansas City Southern'),
    ('MKTX', 'MarketAxess Holdings'),
    ('GPC', 'Genuine Parts'),
    ('IFF', 'Intl Flavors & Fragrances'),
    ('FTNT', 'Fortinet'),
    ('EVRG', 'Evergy'),
    ('WDC', 'Western Digital'),
    ('WAT', 'Waters'),
    ('CXO', 'Concho Resources'),
    ('BKR', 'Baker Hughes'),
    ('DRI', 'Darden Restaurants'),
    ('TIF', 'Tiffany'),
    ('IT', 'Gartner'),
    ('NTAP', 'NetApp'),
    ('AKAM', 'Akamai Technologies'),
    ('DGX', 'Quest Diagnostics'),
    ('WAB', 'Westinghouse Air Brake'),
    ('PFG', 'Principal Financial Group'),
    ('CTL', 'CenturyLink'),
    ('EXPE', 'Expedia Group'),
    ('NLOK', 'NortonLifeLock'),
    ('BR', 'Broadridge Financial Soln'),
    ('STX', 'Seagate Technology'),
    ('GRMN', 'Garmin'),
    ('UDR', 'UDR'),
    ('CAG', 'Conagra Brands'),
    ('GWW', 'W.W. Grainger'),
    ('XYL', 'Xylem'),
    ('CTXS', 'Citrix Systems'),
    ('ULTA', 'Ulta Beauty'),
    ('TTWO', 'Take-Two Interactive'),
    ('HOLX', 'Hologic'),
    ('EXR', 'Extra Space Storage'),
    ('MAS', 'Masco'),
    ('ABC', 'AmerisourceBergen'),
    ('FRC', 'First Republic Bank'),
    ('CBOE', 'Cboe Global Markets'),
    ('L', 'Loews'),
    ('BRK.A', 'Berkshire Hathaway'),
    ('NVR', 'NVR'),
    ('HAS', 'Hasbro'),
    ('FMC', 'FMC'),
    ('EXPD', 'Expeditors International'),
    ('HST', 'Host Hotels & Resorts'),
    ('DRE', 'Duke Realty'),
    ('XRAY', 'Dentsply Sirona'),
    ('ATO', 'Atmos Energy'),
    ('FANG', 'Diamondback Energy'),
    ('LNT', 'Alliant Energy'),
    ('AES', 'AES'),
    ('J', 'Jacobs Engineering Group'),
    ('FOXA', 'Fox'),
    ('HRL', 'Hormel Foods'),
    ('IEX', 'IDEX'),
    ('BF.B', 'Brown-Forman'),
    ('CNP', 'CenterPoint Energy'),
    ('LDOS', 'Leidos Holdings'),
    ('QRVO', 'Qorvo'),
    ('LW', 'Lamb Weston Holdings'),
    ('VAR', 'Varian Medical Systems'),
    ('NDAQ', 'Nasdaq'),
    ('ARNC', 'Arconic'),
    ('SJM', 'JM Smucker'),
    ('SIVB', 'SVB Financial'),
    ('URI', 'United Rentals'),
    ('LNC', 'Lincoln National'),
    ('WYNN', 'Wynn Resorts'),
    ('JKHY', 'Jack Henry & Associates'),
    ('NCLH', 'Norwegian Cruise Line'),
    ('WU', 'The Western Union'),
    ('AAL', 'American Airlines Group'),
    ('UHS', 'Universal Health Services'),
    ('TSCO', 'Tractor Supply'),
    ('AAP', 'Advance Auto Parts'),
    ('ALLE', 'Allegion'),
    ('RJF', 'Raymond James Financial'),
    ('RE', 'Everest Re Group'),
    ('AVY', 'Avery Dennison'),
    ('REG', 'Regency Centers'),
    ('LKQ', 'LKQ'),
    ('EMN', 'Eastman Chemical'),
    ('TXT', 'Textron'),
    ('ANET', 'Arista Networks'),
    ('PKG', 'Packaging Corp of America'),
    ('CMA', 'Comerica'),
    ('DISCK', 'Discovery'),
    ('CHRW', 'C.H. Robinson Worldwide'),
    ('HII', 'Huntington Ingalls Indus'),
    ('WRK', 'WestRock'),
    ('PKI', 'PerkinElmer'),
    ('GL', 'Globe Life'),
    ('VNO', 'Vornado Realty'),
    ('PHM', 'PulteGroup'),
    ('HSIC', 'Henry Schein'),
    ('CF', 'CF Industries Holdings'),
    ('NRG', 'NRG Energy'),
    ('ETFC', 'E*TRADE Financial'),
    ('NBL', 'Noble Energy'),
    ('JBHT', 'JB Hunt Transport Servs'),
    ('NI', 'NiSource'),
    ('PNW', 'Pinnacle West Capital'),
    ('DXC', 'DXC Technology'),
    ('MYL', 'Mylan'),
    ('TAP', 'Molson Coors Brewing'),
    ('MRO', 'Marathon Oil'),
    ('FRT', 'Federal Realty Investment'),
    ('IRM', 'Iron Mountain'),
    ('KIM', 'Kimco Realty'),
    ('WHR', 'Whirlpool'),
    ('ABMD', 'Abiomed'),
    ('DVN', 'Devon Energy'),
    ('FBHS', 'Fortune Brands Home'),
    ('SNA', 'Snap-on'),
    ('ZION', 'Zions Bancorp'),
    ('FFIV', 'F5 Networks'),
    ('NOV', 'National Oilwell Varco'),
    ('IPG', 'Interpublic Gr of Cos'),
    ('BWA', 'BorgWarner'),
    ('JNPR', 'Juniper Networks'),
    ('ALK', 'Alaska Air Group'),
    ('APA', 'Apache'),
    ('MHK', 'Mohawk Industries'),
    ('DISH', 'DISH Network'),
    ('AIV', 'Apartment Inv & Mgmt'),
    ('FTI', 'TechnipFMC'),
    ('CPB', 'Campbell Soup'),
    ('HFC', 'HollyFrontier'),
    ('AIZ', 'Assurant'),
    ('BEN', 'Franklin Resources'),
    ('TPR', 'Tapestry'),
    ('KSS', "Kohl's"),
    ('PNR', 'Pentair'),
    ('XRX', 'Xerox Holdings'),
    ('NWL', 'Newell Brands'),
    ('PBCT', "People's United Finl"),
    ('FLIR', 'FLIR Systems'),
    ('PVH', 'PVH'),
    ('SLG', 'SL Green Realty'),
    ('PRGO', 'Perrigo Co'),
    ('NLSN', 'Nielsen Holdings'),
    ('ALB', 'Albemarle'),
    ('LEG', 'Leggett & Platt'),
    ('RHI', 'Robert Half International'),
    ('MOS', 'Mosaic'),
    ('IVZ', 'Invesco'),
    ('AOS', 'A.O. Smith'),
    ('COG', 'Cabot Oil & Gas'),
    ('NWSA', 'News Corp'),
    ('DVA', 'DaVita'),
    ('UNM', 'Unum'),
    ('FLS', 'Flowserve'),
    ('FOX', 'Fox'),
    ('PWR', 'Quanta Services'),
    ('SEE', 'Sealed Air'),
    ('HOG', 'Harley-Davidson'),
    ('CPRI', 'Capri Holdings'),
    ('RL', 'Ralph Lauren'),
    ('HBI', 'Hanesbrands'),
    ('DISCA', 'Discovery'),
    ('IPGP', 'IPG Photonics'),
    ('ROL', 'Rollins'),
    ('HRB', 'H&R Block'),
    ('M', "Macy's"),
    ('XEC', 'Cimarex Energy'),
    ('LB', 'L Brands'),
    ('ADS', 'Alliance Data Systems'),
    ('HP', 'Helmerich & Payne'),
    ('AMG', 'Affiliated Managers Group'),
    ('JWN', 'Nordstrom'),
    ('GPS', 'Gap'),
    ('UAA', 'Under Armour'),
    ('COTY', 'Coty'),
    ('UA', 'Under Armour'),
    ('TRIP', 'TripAdvisor'),
    ('MAC', 'Macerich'),
    ('LEN.B', 'Lennar'),
    ('NWS', 'News Corp'),
    ('JEF', 'Jefferies Financial Group'),
    ('WH', 'Wyndham Hotels & Resorts')
]