TICKERS = [
    ('AAPL', 'Apple'),
    ('MSFT', 'Microsoft'),
    ('AMZN', 'Amazon.com'),
    ('FB', 'Facebook'),
    ('BRK.B', 'Berkshire Hathaway'),
    ('JPM', 'JPMorgan Chase'),
    ('XOM', 'Exxon Mobil'),
    ('GOOG', 'Alphabet'),
    ('GOOGL', 'Alphabet'),
    ('JNJ', 'Johnson & Johnson'),
    ('BAC', 'Bank of America'),
    ('WFC', 'Wells Fargo'),
    ('CVX', 'Chevron'),
    ('V', 'Visa'),
    ('UNH', 'UnitedHealth Group'),
    ('T', 'AT&T'),
    ('INTC', 'Intel'),
    ('HD', 'Home Depot'),
    ('PFE', 'Pfizer'),
    ('VZ', 'Verizon Communications'),
    ('CSCO', 'Cisco Systems'),
    ('PG', 'Procter & Gamble'),
    ('BA', 'Boeing'),
    ('MA', 'Mastercard'),
    ('C', 'Citigroup'),
    ('NFLX', 'Netflix'),
    ('KO', 'Coca-Cola'),
    ('MRK', 'Merck & Co'),
    ('DIS', 'Walt Disney'),
    ('PEP', 'PepsiCo'),
    ('DWDP', 'DowDuPont'),
    ('CMCSA', 'Comcast'),
    ('NVDA', 'NVIDIA'),
    ('ABBV', 'AbbVie'),
    ('None', 'nan'),
    ('ORCL', 'Oracle'),
    ('PM', 'Philip Morris Intl'),
    ('WMT', 'Walmart'),
    ('MCD', "McDonald's"),
    ('AMGN', 'Amgen'),
    ('ADBE', 'Adobe Systems'),
    ('IBM', 'IBM'),
    ('GE', 'General Electric'),
    ('MMM', '3M'),
    ('MDT', 'Medtronic'),
    ('UNP', 'Union Pacific'),
    ('TXN', 'Texas Instruments'),
    ('HON', 'Honeywell International'),
    ('MO', 'Altria Group'),
    ('ABT', 'Abbott Laboratories'),
    ('ACN', 'Accenture'),
    ('NKE', 'Nike'),
    ('AVGO', 'Broadcom'),
    ('BKNG', 'Booking Holdings'),
    ('CRM', 'Salesforce.com'),
    ('UTX', 'United Technologies'),
    ('PYPL', 'PayPal Holdings'),
    ('SLB', 'Schlumberger'),
    ('GILD', 'Gilead Sciences'),
    ('COST', 'Costco Wholesale'),
    ('BMY', 'Bristol-Myers Squibb'),
    ('TMO', 'Thermo Fisher Scientific'),
    ('QCOM', 'Qualcomm'),
    ('LLY', 'Eli Lilly'),
    ('COP', 'ConocoPhillips'),
    ('CAT', 'Caterpillar'),
    ('NEE', 'NextEra Energy'),
    ('LOW', "Lowe's Companies"),
    ('USB', 'US Bancorp'),
    ('GS', 'Goldman Sachs Group'),
    ('LMT', 'Lockheed Martin'),
    ('UPS', 'United Parcel Service'),
    ('EOG', 'EOG Resources'),
    ('AXP', 'American Express'),
    ('SBUX', 'Starbucks'),
    ('CVS', 'CVS Health'),
    ('MS', 'Morgan Stanley'),
    ('OXY', 'Occidental Petroleum'),
    ('BDX', 'Becton'),
    ('AMT', 'American Tower'),
    ('PNC', 'PNC Financial Services Gr'),
    ('BLK', 'BlackRock'),
    ('SCHW', 'Charles Schwab'),
    ('BIIB', 'Biogen'),
    ('MU', 'Micron Technology'),
    ('ANTM', 'Anthem'),
    ('DHR', 'Danaher'),
    ('MDLZ', 'Mondelez International'),
    ('AET', 'Aetna'),
    ('TJX', 'TJX Companies'),
    ('CB', 'Chubb'),
    ('ADP', 'Automatic Data Processing'),
    ('ATVI', 'Activision Blizzard'),
    ('CL', 'Colgate-Palmolive'),
    ('AGN', 'Allergan'),
    ('CELG', 'Celgene'),
    ('CSX', 'CSX'),
    ('CME', 'CME Group'),
    ('FDX', 'FedEx'),
    ('RTN', 'Raytheon'),
    ('DUK', 'Duke Energy'),
    ('BK', 'Bank of New York Mellon'),
    ('CHTR', 'Charter Communications'),
    ('ISRG', 'Intuitive Surgical'),
    ('SYK', 'Stryker'),
    ('NOC', 'Northrop Grumman'),
    ('SPG', 'Simon Property Group'),
    ('FOXA', 'Twenty-First Century Fox'),
    ('SPGI', 'S&P Global'),
    ('GD', 'General Dynamics'),
    ('WBA', 'Walgreens Boots Alliance'),
    ('GM', 'General Motors'),
    ('INTU', 'Intuit'),
    ('VLO', 'Valero Energy'),
    ('AIG', 'American International Gr'),
    ('PSX', 'Phillips 66'),
    ('SO', 'Southern'),
    ('AMAT', 'Applied Materials'),
    ('CTSH', 'Cognizant Tech Solns'),
    ('PX', 'Praxair'),
    ('DE', 'Deere'),
    ('BSX', 'Boston Scientific'),
    ('COF', 'Capital One Financial'),
    ('CCI', 'Crown Castle Intl'),
    ('D', 'Dominion Energy'),
    ('MET', 'MetLife'),
    ('EMR', 'Emerson Electric'),
    ('ESRX', 'Express Scripts Holding'),
    ('F', 'Ford Motor'),
    ('VRTX', 'Vertex Pharmaceuticals'),
    ('EA', 'Electronic Arts'),
    ('ICE', 'Intercontinental Exchange'),
    ('NSC', 'Norfolk Southern'),
    ('ITW', 'Illinois Tool Works'),
    ('MMC', 'Marsh & McLennan'),
    ('CI', 'Cigna'),
    ('ZTS', 'Zoetis'),
    ('EXC', 'Exelon'),
    ('ILMN', 'Illumina'),
    ('HUM', 'Humana'),
    ('TGT', 'Target'),
    ('BBT', 'BB&T'),
    ('HAL', 'Halliburton'),
    ('PRU', 'Prudential Financial'),
    ('MAR', 'Marriott International'),
    ('APC', 'Anadarko Petroleum'),
    ('KHC', 'Kraft Heinz'),
    ('HPQ', 'HP'),
    ('KMB', 'Kimberly-Clark'),
    ('STZ', 'Constellation Brands'),
    ('BAX', 'Baxter International'),
    ('ECL', 'Ecolab'),
    ('ADI', 'Analog Devices'),
    ('LYB', 'LyondellBasell Industries'),
    ('FIS', 'Fidelity National Info'),
    ('PLD', 'Prologis'),
    ('PGR', 'Progressive'),
    ('APD', 'Air Products & Chemicals'),
    ('AEP', 'American Electric Power'),
    ('STT', 'State Street'),
    ('PSA', 'Public Storage'),
    ('EQIX', 'Equinix'),
    ('SHW', 'Sherwin-Williams'),
    ('AON', 'Aon'),
    ('EBAY', 'eBay'),
    ('KMI', 'Kinder Morgan'),
    ('AFL', 'Aflac'),
    ('TRV', 'Travelers Companies'),
    ('SYY', 'Sysco'),
    ('ETN', 'Eaton'),
    ('WM', 'Waste Management'),
    ('MPC', 'Marathon Petroleum'),
    ('PXD', 'Pioneer Natural Resources'),
    ('ROST', 'Ross Stores'),
    ('ALL', 'Allstate'),
    ('DAL', 'Delta Air Lines'),
    ('EL', 'The Estee Lauder Cos'),
    ('TEL', 'TE Connectivity'),
    ('JCI', 'Johnson Controls Intl'),
    ('STI', 'SunTrust Banks'),
    ('EW', 'Edwards Lifesciences'),
    ('SRE', 'Sempra Energy'),
    ('FISV', 'Fiserv'),
    ('ADSK', 'Autodesk'),
    ('OKE', 'ONEOK'),
    ('HCA', 'HCA Healthcare'),
    ('TWTR', 'Twitter'),
    ('MCO', "Moody's"),
    ('LRCX', 'Lam Research'),
    ('TROW', 'T. Rowe Price Group'),
    ('ROP', 'Roper Technologies'),
    ('WY', 'Weyerhaeuser'),
    ('ALXN', 'Alexion Pharmaceuticals'),
    ('PEG', 'Public Service Enterprise'),
    ('LUV', 'Southwest Airlines'),
    ('MCK', 'McKesson'),
    ('REGN', 'Regeneron Pharmaceuticals'),
    ('VFC', 'VF'),
    ('APH', 'Amphenol'),
    ('GIS', 'General Mills'),
    ('ADM', 'Archer-Daniels Midland'),
    ('PPG', 'PPG Industries'),
    ('YUM', 'Yum Brands'),
    ('CNC', 'Centene'),
    ('DG', 'Dollar General'),
    ('DFS', 'Discover Financial'),
    ('MTB', 'M&T Bank'),
    ('ALGN', 'Align Technology'),
    ('APTV', 'Aptiv'),
    ('ED', 'Consolidated Edison'),
    ('RHT', 'Red Hat'),
    ('SYF', 'Synchrony Finl'),
    ('FTV', 'Fortive'),
    ('AVB', 'AvalonBay Communities'),
    ('MNST', 'Monster Beverage'),
    ('EQR', 'Equity Residential'),
    ('WELL', 'Welltower'),
    ('XEL', 'Xcel Energy'),
    ('WDC', 'Western Digital'),
    ('KR', 'Kroger'),
    ('CCL', 'Carnival'),
    ('FCX', 'Freeport-McMoRan'),
    ('DLR', 'Digital Realty Trust'),
    ('DXC', 'DXC Technology'),
    ('DVN', 'Devon Energy'),
    ('GLW', 'Corning'),
    ('IR', 'Ingersoll-Rand'),
    ('ZBH', 'Zimmer Biomet Holdings'),
    ('WMB', 'Williams Companies'),
    ('ORLY', "O'Reilly Automotive"),
    ('HPE', 'Hewlett Packard'),
    ('DPS', 'Dr Pepper Snapple Group'),
    ('HLT', 'Hilton Worldwide Holdings'),
    ('COL', 'Rockwell Collins'),
    ('NTRS', 'Northern Trust'),
    ('PCG', 'PG&E'),
    ('PCAR', 'PACCAR'),
    ('PAYX', 'Paychex'),
    ('FOX', 'Twenty-First Century Fox'),
    ('IP', 'International Paper'),
    ('MCHP', 'Microchip Technology'),
    ('NTAP', 'NetApp'),
    ('ROK', 'Rockwell Automation'),
    ('CMI', 'Cummins'),
    ('PH', 'Parker Hannifin'),
    ('KEY', 'KeyCorp'),
    ('CXO', 'Concho Resources'),
    ('SWK', 'Stanley Black & Decker'),
    ('EIX', 'Edison Intl'),
    ('TSN', 'Tyson Foods'),
    ('AMP', 'Ameriprise Financial'),
    ('DLTR', 'Dollar Tree'),
    ('WEC', 'WEC Energy Group'),
    ('WLTW', 'Willis Towers Watson'),
    ('VTR', 'Ventas'),
    ('NEM', 'Newmont Mining'),
    ('RF', 'Regions Financial'),
    ('A', 'Agilent Technologies'),
    ('PPL', 'PPL'),
    ('NUE', 'Nucor'),
    ('FITB', 'Fifth Third Bancorp'),
    ('BXP', 'Boston Properties'),
    ('CBS', 'CBS'),
    ('CFG', 'Citizens Financial Group'),
    ('SBAC', 'SBA Communications'),
    ('IDXX', 'IDEXX Laboratories'),
    ('DTE', 'DTE Energy'),
    ('FLT', 'Fleetcor Technologies'),
    ('MSI', 'Motorola Solutions'),
    ('CERN', 'Cerner'),
    ('INFO', 'IHS Markit'),
    ('ES', 'Eversource Energy'),
    ('MYL', 'Mylan'),
    ('LH', 'Laboratory Corp'),
    ('BBY', 'Best Buy Co'),
    ('CTL', 'CenturyLink'),
    ('ANDV', 'Andeavor'),
    ('HIG', 'Hartford Financial'),
    ('AZO', 'AutoZone'),
    ('APA', 'Apache'),
    ('SWKS', 'Skyworks Solutions'),
    ('MRO', 'Marathon Oil'),
    ('RCL', 'Royal Caribbean Cruises'),
    ('GPN', 'Global Payments'),
    ('HES', 'Hess'),
    ('CLX', 'Clorox'),
    ('OMC', 'Omnicom Group'),
    ('K', 'Kellogg'),
    ('ABMD', 'Abiomed'),
    ('HRS', 'Harris'),
    ('VMC', 'Vulcan Materials'),
    ('NBL', 'Noble Energy'),
    ('TDG', 'TransDigm Group'),
    ('TXT', 'Textron'),
    ('VRSK', 'Verisk Analytics'),
    ('NOV', 'National Oilwell Varco'),
    ('XLNX', 'Xilinx'),
    ('AME', 'AMETEK'),
    ('UAL', 'United Continental'),
    ('STX', 'Seagate Technology'),
    ('ETFC', 'E*TRADE Financial'),
    ('HBAN', 'Huntington Bancshares'),
    ('IQV', 'IQVIA Holdings'),
    ('FE', 'FirstEnergy'),
    ('CTAS', 'Cintas'),
    ('GWW', 'W.W. Grainger'),
    ('KLAC', 'KLA-Tencor'),
    ('CMA', 'Comerica'),
    ('AAL', 'American Airlines Group'),
    ('ESS', 'Essex Property Trust'),
    ('RSG', 'Republic Services'),
    ('HST', 'Host Hotels & Resorts'),
    ('WAT', 'Waters'),
    ('O', 'Realty Income'),
    ('CAH', 'Cardinal Health'),
    ('SIVB', 'SVB Financial'),
    ('LLL', 'L3 Technologies'),
    ('AWK', 'American Water Works Co'),
    ('MSCI', 'MSCI'),
    ('EVRG', 'Evergy'),
    ('DGX', 'Quest Diagnostics'),
    ('MTD', 'Mettler-Toledo Int'),
    ('EFX', 'Equifax'),
    ('AEE', 'Ameren'),
    ('RMD', 'ResMed'),
    ('EXPE', 'Expedia Group'),
    ('ANSS', 'Ansys'),
    ('ETR', 'Entergy'),
    ('MGM', 'MGM Resorts Intl'),
    ('EMN', 'Eastman Chemical'),
    ('XL', 'XL Group'),
    ('CBRE', 'CBRE Group'),
    ('WRK', 'WestRock'),
    ('LEN', 'Lennar'),
    ('WYNN', 'Wynn Resorts'),
    ('DHI', 'D.R. Horton'),
    ('CAG', 'Conagra Brands'),
    ('ABC', 'AmerisourceBergen'),
    ('MKC', 'McCormick & Co'),
    ('MLM', 'Martin Marietta Materials'),
    ('TSS', 'Total System Services'),
    ('PFG', 'Principal Financial Group'),
    ('BHGE', 'Baker Hughes'),
    ('EQT', 'EQT'),
    ('FAST', 'Fastenal'),
    ('FTI', 'TechnipFMC'),
    ('MHK', 'Mohawk Industries'),
    ('LNC', 'Lincoln National'),
    ('CTXS', 'Citrix Systems'),
    ('BR', 'Broadridge Financial Soln'),
    ('TPR', 'Tapestry'),
    ('ULTA', 'Ulta Beauty'),
    ('GPC', 'Genuine Parts'),
    ('TTWO', 'Take-Two Interactive'),
    ('TIF', 'Tiffany'),
    ('CMS', 'CMS Energy'),
    ('DRI', 'Darden Restaurants'),
    ('VRSN', 'VeriSign'),
    ('CHD', 'Church & Dwight Co'),
    ('ARE', 'Alexandria Real Estate'),
    ('EXPD', 'Expeditors International'),
    ('KMX', 'CarMax'),
    ('HSY', 'Hershey'),
    ('GGP', 'GGP'),
    ('BF.B', 'Brown-Forman'),
    ('SYMC', 'Symantec'),
    ('SNPS', 'Synopsys'),
    ('L', 'Loews'),
    ('VNO', 'Vornado Realty Trust'),
    ('AKAM', 'Akamai Technologies'),
    ('EXR', 'Extra Space Storage'),
    ('TAP', 'Molson Coors Brewing'),
    ('NWL', 'Newell Brands'),
    ('BLL', 'Ball'),
    ('AMD', 'Advanced Micro Devices'),
    ('KSS', "Kohl's"),
    ('URI', 'United Rentals'),
    ('CDNS', 'Cadence Design Systems'),
    ('HCP', 'HCP'),
    ('IT', 'Gartner'),
    ('SJM', 'JM Smucker'),
    ('HFC', 'HollyFrontier'),
    ('XYL', 'Xylem'),
    ('CNP', 'CenterPoint Energy'),
    ('FMC', 'FMC'),
    ('AJG', 'Arthur J. Gallagher'),
    ('MAS', 'Masco'),
    ('CHRW', 'C.H. Robinson Worldwide'),
    ('CBOE', 'Cboe Global Markets'),
    ('INCY', 'Incyte'),
    ('COO', 'Cooper Companies'),
    ('PVH', 'PVH'),
    ('RJF', 'Raymond James Financial'),
    ('MAA', 'Mid-America Apartment'),
    ('HSIC', 'Henry Schein'),
    ('M', "Macy's"),
    ('DOV', 'Dover'),
    ('KSU', 'Kansas City Southern'),
    ('ADS', 'Alliance Data Systems'),
    ('CA', 'CA'),
    ('HOLX', 'Hologic'),
    ('IVZ', 'Invesco'),
    ('COG', 'Cabot Oil & Gas'),
    ('CMG', 'Chipotle Mexican Grill'),
    ('VAR', 'Varian Medical Systems'),
    ('NDAQ', 'Nasdaq'),
    ('JBHT', 'JB Hunt Transport'),
    ('FFIV', 'F5 Networks'),
    ('ZION', 'Zions Bancorp'),
    ('VIAB', 'Viacom'),
    ('BEN', 'Franklin Resources'),
    ('HAS', 'Hasbro'),
    ('CF', 'CF Industries Holdings'),
    ('PKG', 'Packaging Corp of America'),
    ('ALB', 'Albemarle'),
    ('NLSN', 'Nielsen Holdings'),
    ('DRE', 'Duke Realty'),
    ('HRL', 'Hormel Foods'),
    ('UDR', 'UDR'),
    ('AAP', 'Advance Auto Parts'),
    ('QRVO', 'Qorvo'),
    ('XRAY', 'Dentsply Sirona'),
    ('KORS', 'Michael Kors Holdings'),
    ('CINF', 'Cincinnati Financial'),
    ('LKQ', 'LKQ'),
    ('IRM', 'Iron Mountain'),
    ('LNT', 'Alliant Energy'),
    ('UHS', 'Universal Health Services'),
    ('HII', 'Huntington Ingalls Indus'),
    ('XEC', 'Cimarex Energy'),
    ('NCLH', 'Norwegian Cruise Line'),
    ('DVA', 'DaVita'),
    ('MOS', 'Mosaic'),
    ('IFF', 'Intl Flavors & Fragrances'),
    ('PRGO', 'Perrigo Co'),
    ('JNPR', 'Juniper Networks'),
    ('WHR', 'Whirlpool'),
    ('NRG', 'NRG Energy'),
    ('TSCO', 'Tractor Supply'),
    ('WU', 'The Western Union'),
    ('RE', 'Everest Re Group'),
    ('FRT', 'Federal Realty Investment'),
    ('IPG', 'Interpublic Gr of Cos'),
    ('SNA', 'Snap-on'),
    ('LB', 'L Brands'),
    ('SLG', 'SL Green Realty'),
    ('PNW', 'Pinnacle West Capital'),
    ('REG', 'Regency Centers'),
    ('TMK', 'Torchmark'),
    ('AVY', 'Avery Dennison'),
    ('AES', 'AES'),
    ('NI', 'NiSource'),
    ('DISCK', 'Discovery'),
    ('AOS', 'A.O. Smith'),
    ('BWA', 'BorgWarner'),
    ('UNM', 'Unum'),
    ('IPGP', 'IPG Photonics'),
    ('AMG', 'Affiliated Managers Group'),
    ('RHI', 'Robert Half International'),
    ('HBI', 'Hanesbrands'),
    ('PKI', 'PerkinElmer'),
    ('FBHS', 'Fortune Brands Home'),
    ('NKTR', 'Nektar Therapeutics'),
    ('CPB', 'Campbell Soup'),
    ('PHM', 'PulteGroup'),
    ('JEC', 'Jacobs Engineering Group'),
    ('DISH', 'DISH Network'),
    ('HOG', 'Harley-Davidson'),
    ('ALK', 'Alaska Air Group'),
    ('ALLE', 'Allegion'),
    ('KIM', 'Kimco Realty'),
    ('GPS', 'Gap'),
    ('ARNC', 'Arconic'),
    ('RL', 'Ralph Lauren'),
    ('SEE', 'Sealed Air'),
    ('GRMN', 'Garmin'),
    ('FLIR', 'FLIR Systems'),
    ('HP', 'Helmerich & Payne'),
    ('PNR', 'Pentair'),
    ('JEF', 'Jefferies Financial Group'),
    ('FLR', 'Fluor'),
    ('COTY', 'Coty'),
    ('FL', 'Foot Locker'),
    ('AIV', 'Apartment Inv & Mgmt'),
    ('TRIP', 'TripAdvisor'),
    ('PBCT', "People's United Finl"),
    ('MAC', 'Macerich'),
    ('JWN', 'Nordstrom'),
    ('LEG', 'Leggett & Platt'),
    ('NFX', 'Newfield Exploration'),
    ('GT', 'Goodyear Tire & Rubber'),
    ('NWSA', 'News'),
    ('AIZ', 'Assurant'),
    ('MAT', 'Mattel'),
    ('SRCL', 'Stericycle'),
    ('SCG', 'SCANA'),
    ('EVHC', 'Envision Healthcare'),
    ('FLS', 'Flowserve'),
    ('XRX', 'Xerox'),
    ('PWR', 'Quanta Services'),
    ('BHF', 'Brighthouse Financial'),
    ('HRB', 'H&R Block'),
    ('DISCA', 'Discovery'),
    ('UAA', 'Under Armour'),
    ('UA', 'Under Armour'),
    ('NWS', 'News')
]